# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-01 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaiLian', '0002_auto_20181029_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indeximg', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=50)),
                ('init', models.CharField(max_length=10)),
                ('img1', models.CharField(max_length=255)),
                ('img2', models.CharField(max_length=255)),
                ('img3', models.CharField(max_length=255)),
                ('img4', models.CharField(max_length=255)),
            ],
        ),
    ]
